export const BROWSE_CONTEXT = 'browse'
export const COLLECTION_CONTEXT = 'collection'
export const ITEM_CONTEXT = 'item'
export const VIEWER_CONTEXT = 'viewer'
export const EXHIBITIONS_CONTEXT = 'exhibitions'
